### ISSUE TITLE
extension takes over intellisense for all YAML files, not just porter.yaml

### ISSUE THREAD

**Issue by carolynvs** [getporter/vscode-extension#44]
1. Create a directory with a porter.yaml and a kubernetes manifest.
2. Open the directory in VS Code with the Porter extension enabled.
3. Open the kubernetes manifest first. Note that there are no red squiggles. Now close it.
4. Open the porter.yaml. Now close it.
5. Re-open the kubernetes manifest and note that it is being validated against the Porter extension, red squiggles galore because it is in fact not a porter.yaml.

**porter.yaml**
```yaml
name: HELLO
version: 0.1.0
description: "An example Porter configuration"
tag: getporter/porter-hello

mixins:
  - exec

install:
  - exec:
      description: "Install Hello World"
      command: ./helpers.sh
      arguments:
        - install

upgrade:
  - exec:
      description: "World 2.0"
      command: ./helpers.sh
      arguments:
        - upgrade

uninstall:
  - exec:
      description: "Uninstall Hello World"
      command: ./helpers.sh
      arguments:
        - uninstall
```

**manifests.yaml**
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: demospace
```

![Screen Shot 2020-10-23 at 10 49 58 AM](https://user-images.githubusercontent.com/1368985/97025321-884e4d80-151d-11eb-9d33-817ea055b5dc.png)
