### ISSUE TITLE
Support intellisense for new file types

### ISSUE THREAD

**Issue by carolynvs** [getporter/vscode-extension#47]
In the next porter v1 alpha release, we are introducing some new files that people will be editing by hand:

* credential set
* parameter set
* installation

Here is an example of what they look like. 

Credential Set
```
schemaVersion: 1.0.0
namespace: demo
name: whalegap
credentials:
  - name: kubeconfig
    source:
      path: /Users/carolynvs/.kube/config
```

Parameter Set
```
schemaVersion: 1.0.0
namespace: demo
name: hello-llama
parameters:
  - name: name
    source:
      env: USER
```

Installation
```
schemaVersion: 1.0.0
name: demo
namespace: demo
bundleRepository: carolynvs/tabbycat-demo
bundleVersion: 0.2.1
```

Seems like before porter releases we should tweak the schemaVersion field to indicate which file it is, e.g. `schemaVersion: "credential-set-1.0.0", so that VS code can detect the type of file? Or do you recommend another way, like a separate field like `kind: credential-set`?

Since the schema for these is fixed (unlike porter.yaml), I was thinking that the extension could download the schema from a wellknown url, e.g. https://porter.sh/schema/VERSION/FILE_TYPE.json
